# Generated by Django 4.2 on 2024-06-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxidalias',
            name='wx_alias',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='wxidalias',
            name='wxid',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
