# Generated by Django 4.2 on 2024-06-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0002_alter_wxidalias_wx_alias_alter_wxidalias_wxid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxidalias',
            name='wx_alias',
            field=models.CharField(max_length=60),
        ),
    ]
