# Generated by Django 4.2 on 2024-06-18 19:49

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0003_alter_wxidalias_wx_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wxidalias',
            options={'verbose_name': 'WXID Alias'},
        ),
    ]
