# Generated by Django 4.2 on 2024-06-21 12:54

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0005_hstore_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxidalias',
            name='groups_handles',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wxidalias',
            name='wx_alias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='wxidalias',
            name='wxid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
