# Generated by Django 4.2 on 2024-06-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0006_wxidalias_groups_handles_alter_wxidalias_wx_alias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wxidalias',
            old_name='groups_handles',
            new_name='group_handle',
        ),
        migrations.RenameField(
            model_name='wxidalias',
            old_name='wx_alias',
            new_name='wx_alias1',
        ),
    ]
