# Generated by Django 4.2 on 2024-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0008_wxidalias_wx_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50, unique=True)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='wxidalias',
            options={'verbose_name': 'WXID Aliase'},
        ),
    ]
