# Generated by Django 4.2 on 2024-06-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0009_groupid_alter_wxidalias_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxidalias',
            name='wx_alias',
        ),
    ]
