# Generated by Django 4.2 on 2024-06-22 12:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0010_remove_wxidalias_wx_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxidalias',
            name='wx_alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
