# Generated by Django 4.2 on 2024-06-23 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0011_wxidalias_wx_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxidalias',
            name='wx_alias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
