# Generated by Django 4.2 on 2024-06-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0012_alter_wxidalias_wx_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxidalias',
            name='group_handle',
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.groupid')),
                ('wxid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.wxidalias')),
            ],
        ),
        migrations.AddField(
            model_name='groupid',
            name='wxids',
            field=models.ManyToManyField(through='jobsboard.Handle', to='jobsboard.wxidalias'),
        ),
    ]
