# Generated by Django 4.2 on 2024-06-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0013_remove_wxidalias_group_handle_handle_groupid_wxids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='wx_alias',
        ),
        migrations.RemoveField(
            model_name='job',
            name='wxid',
        ),
        migrations.AddField(
            model_name='job',
            name='wxid_alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.wxidalias'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='wx_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.handle'),
        ),
    ]
