# Generated by Django 4.2 on 2024-06-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0014_remove_job_wx_alias_remove_job_wxid_job_wxid_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='group_name',
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.groupid'),
            preserve_default=False,
        ),
    ]
