# Generated by Django 4.2 on 2024-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0016_candidate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
