# Generated by Django 4.2 on 2024-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0017_siteuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateimage',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatevideo',
            name='thumbnail',
            field=models.FileField(default='', upload_to='videos'),
            preserve_default=False,
        ),
    ]
