# Generated by Django 4.2 on 2024-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0018_candidateimage_thumbnail_candidatevideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevideo',
            name='thumbnail',
            field=models.CharField(),
        ),
    ]
