# Generated by Django 4.2 on 2024-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0019_alter_candidatevideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
