# Generated by Django 4.2 on 2024-08-02 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0020_alter_candidateimage_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevideo',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(['.mp4', '.webm'])]),
        ),
    ]
