# Generated by Django 4.2 on 2024-08-02 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0021_alter_candidatevideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevideo',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])]),
        ),
    ]
