# Generated by Django 4.2 on 2024-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0022_alter_candidatevideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatevideo',
            name='video',
            field=models.FileField(upload_to='videos'),
        ),
    ]
