# Generated by Django 4.2 on 2024-08-08 15:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0023_alter_candidatevideo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='interested_job_types',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='wechat_id',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='job_types_covered',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='wechat_id',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='city',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='job_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='wechat_id',
            field=models.CharField(blank=True),
        ),
    ]
