# Generated by Django 4.2 on 2024-08-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0026_job_accomodation_job_contract_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='accomodation',
        ),
        migrations.AddField(
            model_name='job',
            name='accommodation',
            field=models.CharField(blank=True, choices=[(None, 'Enter accomodation type 输入住房种类'), ('shared', 'Shared Flat 合租'), ('independent', 'Independent Flat 独立'), ('allowance', 'Housing Allowance 住房补贴'), ('none', 'None Provided 无')], null=True),
        ),
    ]
