# Generated by Django 4.2 on 2024-08-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0027_remove_job_accomodation_job_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contract_length',
            field=models.CharField(blank=True, choices=[(None, 'Enter contract length 输入合同期限'), ('one_off', 'One Off 一次性'), ('1_day', '1 Day 一天'), ('1_week', '1 Week 一周'), ('1_month', '1 Month 一月'), ('3_months', '3 Months 三月'), ('6_months', '6 Months 六月'), ('1_year', '1 Year 一年'), ('2_years', '2 Years 两年'), ('5_years', '5 Years 五年'), ('on-going', 'On-going 不限日期')], null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='wx_handle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsboard.handle'),
        ),
        migrations.AlterField(
            model_name='job',
            name='wxid_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsboard.wxidalias'),
        ),
    ]
