# Generated by Django 4.2 on 2024-08-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0028_alter_job_contract_length_alter_job_wx_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsboard.groupid'),
        ),
    ]
