# Generated by Django 4.2 on 2024-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0029_alter_job_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scraped',
            field=models.BooleanField(default=True),
        ),
    ]
