# Generated by Django 4.2 on 2024-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0030_job_scraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
