# Generated by Django 4.2 on 2024-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0031_remove_siteuser_user_type_alter_siteuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxidalias',
            name='wx_alias_requested',
            field=models.BooleanField(default=False),
        ),
    ]
