# Generated by Django 4.2 on 2024-08-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0032_wxidalias_wx_alias_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('payment_method', models.CharField(default='Stripe', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsboard.job')),
            ],
        ),
    ]
