# Generated by Django 4.2 on 2024-08-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0033_promotedjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='jobsboard.job'),
        ),
    ]
