# Generated by Django 4.2 on 2024-08-20 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0034_alter_promotedjob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedjob',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoted', to='jobsboard.job'),
        ),
    ]
