# Generated by Django 4.2 on 2024-08-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0035_alter_promotedjob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotedjob',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
