# Generated by Django 4.2 on 2024-08-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0036_alter_promotedjob_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotedjob',
            name='times_promoted',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
