# Generated by Django 5.1 on 2024-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0038_job_time_updated_promotedjob_time_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='wechat_id',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
