# Generated by Django 5.1 on 2024-08-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0039_alter_siteuser_wechat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='wechat_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
