# Generated by Django 5.1 on 2024-08-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0040_alter_siteuser_wechat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='wechat_id',
            field=models.CharField(blank=True, error_messages={'unique': 'That email address has already been registered. Please use another one.'}, null=True, unique=True),
        ),
    ]
