# Generated by Django 5.1 on 2024-09-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0042_alter_siteuser_wechat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle', to='jobsboard.groupid'),
        ),
        migrations.AlterField(
            model_name='handle',
            name='wxid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handle', to='jobsboard.wxidalias'),
        ),
    ]
