# Generated by Django 5.1 on 2024-09-13 14:57

import jobsboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0043_alter_handle_group_alter_handle_wxid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siteuser',
            managers=[
                ('objects', jobsboard.models.CustomUserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='years_experience',
            new_name='experience',
        ),
    ]
