# Generated by Django 5.1.1 on 2024-09-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0044_alter_siteuser_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxidalias',
            name='wx_alias1',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(error_messages={'unique': 'A job with this job description already exists. Please do not copy and paste job descriptions across jobs.'}, unique=True),
        ),
    ]
