# Generated by Django 5.1.1 on 2024-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0045_remove_wxidalias_wx_alias1_alter_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd_translation',
            field=models.TextField(default=''),
        ),
    ]
