# Generated by Django 5.1.1 on 2024-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0046_job_jd_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Ad Messages',
            },
        ),
    ]
