# Generated by Django 5.1.1 on 2024-10-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0047_admessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wxidalias',
            name='wx_alias_requested',
        ),
    ]
