# Generated by Django 5.1.1 on 2024-10-02 14:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0048_remove_wxidalias_wx_alias_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxidalias',
            name='wx_alias_request_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsboard.candidate'),
        ),
        migrations.AddField(
            model_name='wxidalias',
            name='wx_alias_requests_sent_by_me',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, default=list, null=True, size=None),
        ),
    ]
