# Generated by Django 5.1.1 on 2024-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0049_wxidalias_wx_alias_request_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxidalias',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
