# Generated by Django 5.1.1 on 2024-12-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsboard', '0050_wxidalias_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='wechat_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
